/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{html,ts,scss}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Light mode colors (existing)
        'on-primary-fixed-variant': '#00419d',
        'surface-container': '#efedee',
        'surface-container-highest': '#e3e2e3',
        'on-tertiary-container': '#4a3f00',
        'inverse-primary': '#b1c5ff',
        'on-surface': '#1b1c1d',
        'inverse-on-surface': '#f2f0f1',
        'on-secondary-fixed-variant': '#42474b',
        'tertiary-container': '#bfab49',
        'tertiary-fixed': '#f9e37a',
        'primary': '#094cb2',
        'on-primary-fixed': '#001946',
        'on-secondary-fixed': '#171c20',
        'secondary-fixed': '#dfe3e8',
        'on-primary-container': '#e7ebff',
        'background': '#faf9fa',
        'inverse-surface': '#303031',
        'surface-container-low': '#f5f3f4',
        'on-error-container': '#93000a',
        'on-secondary': '#ffffff',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'surface-bright': '#faf9fa',
        'primary-container': '#3366cc',
        'primary-fixed-dim': '#b1c5ff',
        'error-container': '#ffdad6',
        'on-secondary-container': '#606569',
        'on-tertiary-fixed': '#211b00',
        'error': '#ba1a1a',
        'surface-tint': '#2259bf',
        'secondary-fixed-dim': '#c2c7cc',
        'outline': '#737784',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#e9e8e9',
        'primary-fixed': '#d9e2ff',
        'surface': '#faf9fa',
        'outline-variant': '#c3c6d5',
        'on-surface-variant': '#434653',
        'tertiary': '#6d5e00',
        'tertiary-fixed-dim': '#dcc661',
        'surface-variant': '#e3e2e3',
        'surface-dim': '#dbdadb',
        'on-background': '#1b1c1d',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#dfe3e8',
        'secondary': '#5a5f63',
        'on-tertiary-fixed-variant': '#524600',

        // Dark mode colors
        'dark': {
          'deep-navy': '#0F172A',
          'on-secondary-container': '#9CA3AF',
          'on-secondary': '#ffffff',
          'on-error': '#ffffff',
          'error': '#ba1a1a',
          'surface-container-high': '#1E293B',
          'on-primary-container': '#b0c5ff',
          'secondary': '#94A3B8',
          'tertiary': '#F9E37A',
          'surface-container': '#111827',
          'on-secondary-fixed-variant': '#94A3B8',
          'tertiary-fixed': '#f8e37f',
          'surface-ivory': '#0F172A',
          'primary-fixed': '#dae2ff',
          'tertiary-container': '#4A3F00',
          'tertiary-fixed-dim': '#dbc766',
          'on-primary': '#ffffff',
          'secondary-fixed': '#334155',
          'primary': '#3B82F6',
          'on-primary-fixed-variant': '#b1c5ff',
          'error-container': '#410002',
          'on-background': '#F1F5F9',
          'on-tertiary-fixed': '#211b00',
          'outline': '#475569',
          'inverse-primary': '#003686',
          'on-tertiary-fixed-variant': '#524600',
          'surface-dim': '#0F172A',
          'secondary-container': '#334155',
          'outline-variant': '#334155',
          'on-error-container': '#ffdad6',
          'on-tertiary-container': '#f8e37f',
          'on-tertiary': '#000000',
          'inverse-surface': '#faf9fa',
          'on-secondary-fixed': '#f1f5f9',
          'border-subtle': '#334155',
          'surface-container-highest': '#334155',
          'surface-tint': '#3B82F6',
          'on-surface-variant': '#94A3B8',
          'inverse-on-surface': '#1b1c1d',
          'primary-container': '#1E40AF',
          'surface-bright': '#1E293B',
          'surface-container-low': '#111827',
          'on-surface': '#F1F5F9',
          'surface': '#0F172A',
          'background': '#0F172A',
          'surface-variant': '#1E293B',
          'on-primary-fixed': '#001946',
          'accent-gold': '#F9E37A',
          'surface-container-lowest': '#020617',
          'secondary-fixed-dim': '#c2c7cc',
          'primary-fixed-dim': '#b1c5ff',
        },
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Noto Serif', 'serif'],
        display: ['Noto Serif', 'serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Public Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

